apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: "cilium-pool-primary"
spec:
  allowFirstLastIPs: "No"
  blocks:
  - cidr: "192.168.80.0/22"

# deprecated/removed spec
#  cidrs:
#  - cidr: "192.168.80.0/22"
